### 모든 이름 조회
GET http://localhost:5045/api/name
Accept: application/json

### 새로운 이름 추가
POST http://localhost:5045/api/name
Content-Type: application/json

{
  "name": ""
}

### 새로운 이름 추가
POST http://localhost:5045/api/name
Content-Type: application/json

{
  "name": "123456789012345678901234567890123456789012345678901"
}

### 새로운 이름 추가
POST http://localhost:5045/api/name
Content-Type: application/json

{
  "name": "차은우"
}

### 새로운 이름 추가
POST http://localhost:5045/api/name
Content-Type: application/json

{
  "name": "카리나"
}

### 이름 삭제
DELETE http://localhost:5045/api/name/0
Accept: application/json